source 'http://rubygems.org'

gem 'autoprefixer-rails'
gem 'better_errors'
gem 'binding_of_caller'
gem 'bootstrap-sass'
gem 'coffee-rails'
gem 'dispatcher'
gem 'font-awesome-sass'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'paperclip'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'sass-rails'
gem 'sdoc'
gem 'spring'
gem 'sqlite3'
gem 'therubyracer'
gem 'turbolinks'
gem 'uglifier'

# Engines
gem 'company', path: 'engines/company'
gem 'libs', path: 'engines/libs'
gem 'ivr', path: 'engines/ivr'